config/routes.rb
Jobmarking::Application.routes.draw do
  resources :jobs

  resources :lookups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/lookup.rb
require 'public_suffix'
require 'open-uri'

class Lookup
  include Mongoid::Document
  include Mongoid::Timestamps

  field :example_page
  field :domain
  field :company
  field :title
  field :description
  field :location
  field :logo
  field :other_domain_hits, type: Integer
  field :is_deleted, type: Boolean, default: false

  field :destroy_notices, type: Array

  before_save :generate_domain

  validates_presence_of :example_page, :title, :description, :location
  validates_format_of :example_page, :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
  
  #scope :active, where( domain: /[^(_d)]$/i )
  scope :active, where( is_deleted: false )

  #scope :inactive, where( domain: /[(_d)]$/i )
  scope :inactive, where( is_deleted: true )

  protected
  def generate_domain
    self.domain ||= PublicSuffix.parse(URI.parse( self.example_page ).host).sld.downcase if self.example_page.present?
  end
  
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.active

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lookups }
    end
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/new
  # GET /lookups/new.json
  def new
    @lookup = Lookup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/1/edit
  def edit
    @lookup = Lookup.find(params[:id])
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(params[:lookup])

    if (params[:preview])
      @job_params_hash = generate_job_params(@lookup)

      @lookup.example_page = @job_params_hash[:actual_url]

      @all_values_present = all_values_present?(@job_params_hash)

      respond_to do |format|
        format.html { render action: "new"}
        format.json { render json: @job_params_hash.merge( success: @all_values_present )}
      end

    elsif (params[:submit])
      respond_to do |format|
        if @lookup.save
          format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
          format.json { render json: @lookup, status: :created, location: @lookup }
        else
          format.html { render action: "new" }
          format.json { render json: @lookup.errors, status: :unprocessable_entity }
        end
      end

    elsif (params[:unparseable])
      respond_to do |format|
        old_longo = Longo.find_by(:url => @lookup.example_page, :reason => 'Failed XPath parse')

        if old_longo.blank?
          Longo.create(:level => 'WARN', :reason => 'Failed XPath parse',
                       :lookup => @lookup.attributes, :url => @lookup.example_page, :t => DateTime.now.strftime)
        end

        format.html { redirect_to lookups_path, notice: 'Issue reported. Thanks for the help!'}
      end
    end


  end

  # PUT /lookups/1
  # PUT /lookups/1.json
  def update
    @lookup = Lookup.find(params[:id])

    if (params[:preview])
      @lookup.assign_attributes params[:lookup]
      @job_params_hash = generate_job_params(@lookup)

      @lookup.example_page = @job_params_hash[:actual_url]

      @all_values_present = all_values_present?(@job_params_hash)

      respond_to do |format|
        format.html { render action: "new"}
        format.json { render json: @job_params_hash.merge( success: @all_values_present)}
      end

    else

      respond_to do |format|
        if @lookup.update_attributes(params[:lookup])
          format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @lookup.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup = Lookup.find(params[:id])
    if @lookup.example_page && @lookup.domain
      @lookup.domain += '_d'
      @lookup.is_deleted = true
      @lookup.save
    else
      @lookup.destroy
    end

    respond_to do |format|
      format.html { redirect_to lookups_url }
      format.json { head :no_content }
    end
  end

  protected
  def all_values_present?(job_params_hash)
    all_values_present = job_params_hash.reduce (true) { |memo, (k, v)|
      if [:logo, :company].include? k
        memo && true
      else
        memo && v.present?
      end
    }

    return all_values_present
  end

  def generate_job_params(lookup)
    parser = JobUrlParser.new(lookup.example_page)
    return parser.generate_params_given_lookup lookup
  end


end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/lookups/_form.html.haml
%legend You are the star of our society !
.row
  .span6
    = simple_form_for(@lookup) do |f|
      = f.error_notification

      .form-inputs
        = f.input :example_page, :input_html => { :class => 'input-xlarge'}
        = f.input :company, :input_html => { :class => 'input-xxlarge input-xpath'}
        = f.input :title, :input_html => { :class => 'input-xxlarge input-xpath'}
        = f.input :description, :input_html => { :class => 'input-xxlarge input-xpath'}
        = f.input :location, :input_html => { :class => 'input-xxlarge input-xpath'}
        = f.input :logo, :input_html => { :class => 'input-xxlarge input-xpath'}

      .form-actions
        - if @all_values_present
          = f.button :submit, 'Submit', :name => 'submit'
        - else
          = f.button :submit, 'Preview', :name => 'preview'
          - if @job_params_hash
            = f.button :submit, 'Report parsing issue', :name => 'unparseable', :class => 'btn-warning btn'
            %span.badge.badge-important
              Check Abridged Preview for missing values

  .span6
    - if @job_params_hash
      %div#jobs_params_preview.well
        %legend Abridged Preview
        - @job_params_hash.each do |k,v|
          %p
            %span{:class => "#{v.present? ? 'badge' : 'badge badge-important'}"}
              %b= k.to_s.upcase
            = v.slice(0..200) if v.present?

    %div.alert#xpath_info_well
      Please refer
      %a{ :href => 'http://www.w3schools.com/xpath/default.asp', :target => '_blank' } XPath Tutorial
      to add the correct XPaths for each of the fields respectively. Clicking preview will display an
      excerpt of the respective fields found on the example page, if the xpaths were correct.

app/views/lookups/edit.html.haml
%h1 Editing lookup

= render 'form'

= link_to 'Show', @lookup
\|
= link_to 'Back', lookups_path

app/views/lookups/index.html.haml
%div.well.well-large
  - @lookups.each do |lookup|
    %span.lookup_span= link_to escape_javascript(lookup.domain), lookup
    
%legend Help us improve by adding more lookups

= link_to 'Create Lookup', new_lookup_path

app/views/lookups/new.html.haml
= render 'form'

= link_to 'Back', lookups_path

app/views/lookups/show.html.haml
%div#jobs_params_preview.well
  %p
    %span.badge
      %b Domain
    = @lookup.domain
  %p
    %span.badge
      %b Title
    = @lookup.title
  %p
    %span.badge
      %b Company
    = @lookup.company
  %p
    %span.badge
      %b Description
    = @lookup.description
  %p
    %span.badge
      %b Location
    = @lookup.location
  %p
    %span.badge
      %b Example Page
    = @lookup.example_page

= link_to 'Edit', edit_lookup_path(@lookup), :class => 'btn-info btn'
= link_to 'Destroy', @lookup, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'