config/routes.rb
Jobmarking::Application.routes.draw do
  resources :jobs

  resources :lookups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/job.rb
class Job
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :url
  field :title
  field :description
  field :location
  field :company
  field :logo
  
  field :actual_url
  field :active, type: Boolean, default: true
  field :inherited, type: Boolean, default: false

  field :note

  field :geo_code, type: Array

  belongs_to :user
  
  validates_presence_of :url
  validates_format_of :url, :actual_url, :logo,
                      :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix

  scope :active, where( active: true, inherited:false )
  scope :inactive, where( active: false)
  
  scope :by_user, ->(curr_user) {
    where( user: curr_user )
  }

  scope :near_to, ->(param) {
    within_spherical_circle(geo_code: [param, (250.0/3959.0).to_f ])
  }

  def geocode_location
    Rails.logger.info 'Before saving job'

    begin
    if(self.location.present? && self.geo_code.blank?)
      geo_task = GeocodeTask.new self
      self.geo_code= geo_task.perform
    else
      Longo.create(reason: 'Location not found', job: self.attributes, t: DateTime.now.strftime)
    end
    rescue Exception => e
      Longo.create(reason: "Exception #{e.message}", details: e.backtrace)
    end
    Rails.logger.info "Successfully saved job #{self.actual_url}"

  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.by_user(current_user).page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @short_job = Job.new
    @short_job.user=current_user
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @short_job }
    end
  end

  # GET /jobs/1/edit
  def edit
    temp_job = Job.find(params[:id])
    
    if temp_job.user == current_user
      @job = temp_job
    else
      @job = Job.new
      @job.user = current_user
      @job.inherited = true
      
      logger.debug temp_job
      temp_job.attributes.each { |attr|
        logger.debug attr
        if attr[0].in? ['url', 'title', 'location', 'description', 'actual_url', 'company', 'active']
          @job.send( attr[0].to_s + '=', attr[1])
        end  
      }

      # If old job with same actual url is stored, then get rid of it
      old_job = Job.find_by(actual_url: @job.actual_url)
      if old_job.present?
        old_job.destroy
      end

      @job.save!
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create

    @job = Job.new(params[:job])
    
    unless @job.user == current_user
      @job.user = current_user
    end

    job_params = JobUrlParser.new(@job.url).job_params
    @job.assign_attributes job_params

    if @job.user == current_user
      old_job = Job.find_by(actual_url: @job.actual_url)
      if old_job.present?
        @job.id=old_job.id
      end
    end

    @job.geocode_location

    respond_to do |format|
      if @job.save
        if job_params[:confidence].eql? 'high'
          format.html { redirect_to @job, notice: 'Job was successfully created.' }
        else
          format.html { redirect_to edit_job_path(@job), notice: 'Please verify the details below.' }
        end

        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    
    @job = Job.find(params[:id])

    unless @job.user == current_user
      @job.user = current_user
      Job.find(params[:id]).attributes.each { |attr|
        if attr[0].in? ['url', 'title', 'location', 'description', 'actual_url', 'company', 'active']
          @job.send( attr[0].to_s + '=', attr[1])
        end  
      }
    end
    @job.assign_attributes(params[:job])
    @job.geocode_location

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    
    if @job.user == current_user
      @job.destroy
    end

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job) do |f|
  = f.error_notification

  .form-inputs
    - if @job.logo.present?
      = image_tag @job.logo
    = f.input :url, :input_html => { :class => 'input-xxlarge' } if @job.url.blank?
    = f.input :company, :input_html => { :class => 'input-large' } if @job.company.blank?
    = f.input :location, :input_html => { :class => 'input-xlarge' } if @job.location.blank?

    = f.input :note, :label => 'Private Note', :as => :text, :input_html => { :class => 'input-xxlarge', :rows => 5 }


  .form-actions
    = f.button :submit

app/views/jobs/_job.html.haml
%article{:class => full ? 'job_article' : 'job_article span5'}
  %legend.job_legend
    =link_to job_path(j), class: 'job_title' do
      = Sanitize.clean( full ? j.title : j.title.slice(0..100) ) if j.title.present?
      %i.icon-link
    %br
    = image_tag j.logo, class: (full ? 'job_logo_big' : 'job_logo') if j.logo.present?
    -if j.company.present?
      %span.job_company_display.badge.badge-success
        = Sanitize.clean( full ? j.company : j.company.slice(0..20) )
    .job_location_display
      = Sanitize.clean( full ? j.location : j.location.slice(0..50) ) if j.location.present?
      - if j.geo_code.present? && j.geo_code[0].present? && j.geo_code[1].present?
        %a{ href: "/?near=#{j.geo_code[0]},#{j.geo_code[1]}"}
          Search near this
          %i.icon-map-marker
  -if j.description.present?
    .job_description_display
      = Sanitize.clean( full ? j.description : (j.description.slice(0..250) + '...') ) if j.description.present?
  -if show_actions
    .job_actions
      = link_to edit_job_path(j) do
        %i.icon-bookmark
        = owner ? 'Edit' : 'Save'
      = link_to '#' do # TODO Implement popover
        %i.icon-share
        Share
      -if owner
        = link_to 'Destroy', j, :method => :delete, :data => { :confirm => 'Are you sure?' }
      = link_to j.url, target: '_blank' do
        %i.icon-share-alt
        Apply

app/views/jobs/_short_form.html.haml
- if @short_job
  #short_form
    = form_for( @short_job) do |f|
      -# = f.error_notification
      .input-append
        = f.text_field( :url, :class => 'span5', :id => 'appendedInputButton' )
    
        = f.submit( :class => 'btn btn-success span2', :value => 'Save Job' )

app/views/jobs/edit.html.haml
%legend Hope you find this job useful

= render :partial => 'jobs/job', :locals => { :j => @job, :full => true, :owner => true, :show_actions => false }
= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%legend Your dream jobs

- @jobs.each do |job|
  = render :partial => 'jobs/job', :locals => { :j => job, :full => false, :owner => true, :show_actions => true }

= paginate @jobs

app/views/jobs/show.html.haml
= render :partial => 'jobs/job', :locals => { :j => @job, :full => true, :owner => true, :show_actions => true }

= link_to '<-- My Saved Jobs', jobs_path