config/routes.rb
Jobmarking::Application.routes.draw do
  resources :jobs

  resources :lookups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    = link_to 'Improve our Parser', lookups_path
    \|
    = link_to 'Report Issues', 'https://github.com/dahotre/Jobmarking/issues/new'
    \|
    = link_to 'http://www.mongodb.org', target: '_blank' do
      %img.mongo_power{src: 'http://www.mongodb.org/static/images/powered_by/PoweredMongoDBgreen50.png'}
    \|
    %span.muted
      © 2013 Aniket Dahotre. All rights reserved.

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%a{ 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse', :class => 'btn btn-navbar'}
  %i.icon-cogs
= link_to "Jobmarking", root_path, :class => 'brand'
.nav-collapse.collapse
  %ul.nav.pull-right
    %li
      = link_to "Explore Jobs", root_path
    - if user_signed_in?
      %li
        = link_to 'Saved Jobs', jobs_path
      %li.dropdown
        %a{ :href=> '#', :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'}
          = gravatar_image current_user.email
          = current_user.name.present? ? current_user.name.slice(0..10) : current_user.email.slice(0..10)
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to 'Edit account', edit_user_registration_path
          %li
            = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    - else
      %li
        = link_to 'Sign up', new_user_registration_path
      %li
        = link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Jobmarking"
      %meta{:content => content_for?(:description) ? yield(:description) : "Jobmarking", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span7.offset2
            = render 'jobs/short_form'
        .row
          .span12
            = render 'layouts/messages'
            = yield
    = render 'layouts/footer'